name: GitHub Actions Demo
on: [push]
jobs: 
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:

      - name: Echo OS of build agent
        run: | 
          echo "The build agent uses OS: $RUNNER_OS“